### ISSUE TITLE
can we mark this plugin @threadSafe 

### ISSUE THREAD

**Issue by liyi3c** [societe-generale/arch-unit-maven-plugin#53] opened 2023-04-06 08:35 UTC
## Summary

when run maven in multi-thread, it warns 'The following plugins are not marked@threadSafe'
if this plugin is thread safe, I think the solution is just add threadSafe=true as following

@Mojo(... threadSafe=true)

## Type of Issue
It is a : 
 - [ ] bug
 - [ x] request
 - [ ] question regarding the documentation

## Motivation
to support multi-thread without warning msg

## Current Behavior
warn msg

## Expected Behavior
no warning msg

## Steps to Reproduce (for bugs)
run a multi module maven project in multi-thread mode

**Comment by vincent-fuchs** [comment] 2023-04-10 07:33
hi, thanks for raising the question ! I will be honest, I have no idea what to be careful with before declaring it as `threadSafe`.. I guess it is, because we don't do anything too fancy but I am not 100% sure.

**Comment by vincent-fuchs** [comment] 2023-04-10 07:34
duplicate of https://github.com/societe-generale/arch-unit-maven-plugin/issues/50 - closing this one

**Closed by vincent-fuchs** 2023-04-10 07:34 UTC

**Comment by liangjihua** [comment] 2024-02-13 05:41
@vincent-fuchs Hello, I think I just found an issue that arch-unit-maven-plugin used  together with `mvn -T`. 
When freeze rules are used together with multithreading on a multi-module project, these freeze rules will affect each other.

 My project like: 
```
|- root
    |- custom-rules
        |- src
        |- pom.xml
    |- child-one
        |- freeze-rules
            |- stored.rules
        |- src
        |- pom.xml
    |- child-two
        |- freeze-rules
            |- stored.rules
        |- src
        |- pom.xml
    |- pom.xml
```

When build it without `-T`, it will success. But if build it with `mvn -T` it will fail, and report violations.
